config/routes.rb
Rails.application.routes.draw do
  root to: 'power_generators#index'

  resources :home, only: %i[index]
  resources :recommended_searches, only: %i[ new create show ]

  resources :power_generators, only: %i[index show] do
    get 'search', on: :collection
    get 'recommended_search', on: :collection
    get 'recommended_search_result', on: :collection
    get 'freight', on: :member
    get 'calculation_freight', on: :member
  end

  resources :freight, only: %i[] do
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/freight.rb
class Freight < ApplicationRecord
  validates :state, :weight_min, :weight_max, :cost, presence: true
end

app/models/power_generator.rb
class PowerGenerator < ApplicationRecord
  validates :name, :description, :image_url, :manufacturer, :price, :kwp, presence: true
  validates :height, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 40 }
  validates :width, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 100 }
  validates :lenght, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 200 }
  validates :weight, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 3000 }

  enum structure_type: %i[
    metalico
    ceramico
    fibrocimento
    laje
    solo
    trapezoidal
  ]

  def self.search(search)
    return unless search

    where('name LIKE :param or description LIKE :param', param: "%#{search}%")
  end

  def self.freight(address, power_generator)
    freight = Freight.all
    freight.where('state LIKE :state and weight_min <= :weight and weight_max >= :weight', state: "%#{address[:state]}%", weight: "#{power_generator[:weight]}")
  end

  def self.recommended_search(params)
    search = all
    search = where(['price <= ?', 30_000.00]) if params[:lowest_cost].present?
    search = where(['weight <= ?', 200]) if params[:lower_weight].present?
    search = where(['size <= ?', 0.5]) if params[:lower_size].present?
    search = where('name LIKE :param or description LIKE :param', {param: "%#{params[:keyword]}%"}) if not params[:keyword].nil?
    search = where('structure_type = ?', params[:structure_type]) if not params[:structure_type].nil?

    search = order(:price) if params[:lowest_cost].present?
    search = order(:weight) if params[:lower_weight].present?
    search = order(:size) if params[:lower_size].present?
  end
end

app/models/recommended_search.rb
class RecommendedSearch < ApplicationRecord

  def search_power_generators
    power_generators = PowerGenerator.all
    power_generators = power_generators.where(["price <= ?", 30000.00]) if lowest_cost.present?
    power_generators = power_generators.where(["weight <= ?", 200]) if lower_weight.present?
    power_generators = power_generators.where(["size <= ?", 0.5]) if lower_size.present?
    power_generators = power_generators.where("name LIKE :param or description LIKE :param", {param: "%#{keyword}%"}) if keyword.present?
    power_generators = power_generators.where("structure_type = ?", structure_type) if structure_type.present?


    power_generators = power_generators.order(:price) if lowest_cost.present?
    power_generators = power_generators.order(:weight) if lower_weight.present?
    power_generators = power_generators.order(:size) if lower_size.present?
    return power_generators
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/freight_controller.rb
class FreightController < ApplicationController
  def cep
      @address = Correios::CEP::AddressFinder.get(params[:cep])
      ender json: @address, status: :create
  end
end

app/controllers/power_generators_controller.rb
class PowerGeneratorsController < ApplicationController
  before_action :pagination, only: %i[index show]

  def index; end

  def show
    @power_generator = PowerGenerator.find(params[:id])
    return unless params[:cep].present?

    @address = calculate_cep
    return flash.now[:notice] = 'CEP não encontrado' if @address.empty?

    @power_generator_freight = PowerGenerator.freight(@address, @power_generator)
  end

  def search
    @power_generators = PowerGenerator.search(params[:search_power_generator])

    if @power_generators.empty?
      flash.now[:error] = 'Descupe! não encontramos nenhum produto'
    else
      flash.now[:notice] = 'Encontramos esse(s) produto(s)'
    end
  end

  def recommended_search
    byebug
    @power_generators = PowerGenerator.recommended_search(params)
    # render recommended_search_result_power_generators_path
    byebug
  end

  private

  def power_generator_params
    params.require(:power_generator).permit(:name, :description, :image_url, 
                                            :manufacturer, :structure_type, 
                                            :price, :height, :width, :length,
                                            :weight, :kwp, :size, :cost_benefit)
  end
  
  def calculate_cep
    Correios::CEP::AddressFinder.get(params[:cep])
  end
  
  def pagination
    products_by_page = 6
    @array_num_pages = (1 .. ( (PowerGenerator.all.length / products_by_page.to_f).ceil )).to_a
    @page = params.fetch(:page, 0).to_i
    @power_generators = PowerGenerator.offset(@page * products_by_page).limit(products_by_page)
  end

end

app/controllers/recommended_searches_controller.rb
class RecommendedSearchesController < ApplicationController
  def new
    @recommended_search = RecommendedSearch.new
  end

  def create
    @recommended_search = RecommendedSearch.create!(recommended_search_params)
    @recommended_search.save
    
    redirect_to @recommended_search
  end

  def show
    @recommended_search = RecommendedSearch.find(params[:id])
  end

  
  private
  def recommended_search_params
    params.require(:recommended_search).permit(:lowest_cost, :cost_benefit,
                                               :lower_weight, :lower_size, :keyword, 
                                               :structure_type)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/freight_helper.rb
module FreightHelper
end

app/helpers/recommended_searches_helper.rb
module RecommendedSearchesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portal Solar - Dev Test</title>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag 'favicon.png' %>
    <%= javascript_pack_tag 'application' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<div>
  <div class="header">
    <div class="logo"><%= link_to image_tag('ps_logo.png'), root_path %></div>
    <div class="header__title">Geradores de Energia</div>
  </div>

  <div class="searcher gradient">
    <div class="searcher__radio">
      <div class="form-check">
        <input class="form-check-input" type="radio" name="searchRadio" id="simpleSearch" value="simple" checked>
        <label class="form-check-label" for="simpleSearch">Pesquisa simples</label>
      </div>
      <div class="form-check">
        <input class="form-check-input" type="radio" name="searchRadio" id="advancedSearch" value="advanced">
        <label class="form-check-label" for="advancedSearch">Pesquisa Avançada</label>
      </div>
    </div>

    <%= form_tag(search_power_generators_path, method: :get) do %>
      <div class="simple-form">
        <div class="simple-form__input">
          <input class="form-control form-control-lg" type="text" placeholder="o que procura?" name='search_power_generator'>
        </div>
        <div class="simple-form__btn">
          <button type="submit" class="btn btn-outline-primary btn-lg">Pesquisar</button>
        </div>
      </div>
    <% end %>
    <div class="advanced-form" style="display:none;">
      <%= link_to 'Recomendados para você', new_recommended_search_path %> 
    </div>
  </div>

  <body>
    <%= yield %>
  </body>
</html>

app/views/power_generators/_form_cost.html.erb
<p><%= "CEP inserido: #{@address[:zipcode]} "%></p>
<p><%= "Local: #{@address[:city]} - #{@power_generator_freight.first.state} "%></p>
<p><%= "Custo: #{@power_generator_freight.first.cost} "%></p>

app/views/power_generators/_search_form.html.erb
<div class="container">
  <% @power_generators.each do |power_generator| %>
    <div class="box card power_generator-card">
      <%= link_to image_tag(power_generator.image_url), power_generator %>
      <div class="power_generator-card__body">
          <h2><%= link_to (power_generator.name.upcase), power_generator %></h2>
          <p class="power_generator-card__price"><%= number_to_currency(power_generator.price, unit: "R$ ", precision: 2, :separator => ",", :delimiter => ".") %></p>
          <p><strong>Descrição: </strong><%= power_generator.description %></p>
      </div>
    </div>
  <% end %>
</div>

app/views/power_generators/freight.html.erb
<%= form_tag(calculation_freight_power_generator_path, method: :get) do %>
    <input class="form-control form-control-lg" type="text" placeholder="CEP" name='cep'>
    <button type="submit" class="btn btn-outline-primary btn-lg">Calcular</button>
<% end %>   

app/views/power_generators/index.html.erb
<div>
  <%= link_to 'Recomendados para você 1', new_recommended_search_path %> 
  <%= link_to 'Recomendados para você', recommended_search_power_generators_path %> 
</div>
<div class="container" >
  <% @power_generators.each do |power_generator| %>
    <div class="box card power_generator-card">
      <img class="power_generator-card__img">
        <%= link_to image_tag(power_generator.image_url), power_generator %>
      </img>
      <div class="power_generator-card__body">
        <h2><%= link_to (power_generator.name.upcase), power_generator %></h2>
        <p class="power_generator-card__price"><%= number_to_currency(power_generator.price, unit: "R$ ", precision: 2, :separator => ",", :delimiter => ".") %></p>
        <p><strong>Descrição: </strong><%= power_generator.description %></p>
      </div>
    </div>
  <% end %>
</div>

<%if @page > 0 %>
  <%= link_to 'Voltar |', power_generators_path(page: @page - 1) %>
<%end%>

<% @array_num_pages.each do |number_page|%>

  <%= link_to "#{number_page}", power_generators_path(page: (number_page - 1)) %>
<%end%>

<%if @page < @array_num_pages.last - 1 %>
  <%= link_to '| Avançar', power_generators_path(page: @page + 1) %>
<%end%>

app/views/power_generators/recommended_search.html.erb
Nós queremos saber mais sobre o que você procura. Responda as perguntas abaixo:

<%= form_tag(@recommended_search, method: :get) do %>
  <%= check_box_tag :lowest_cost %>
  <%= label_tag(:lowest_cost, 'Menor custo')%>
  <%= check_box_tag :lower_weight %>
  <%= label_tag(:lower_weight, 'Menor Peso')%>
  <%= check_box_tag :lower_size %>
  <%= label_tag(:lower_size, 'Menor Peso')%>
  <%= text_field_tag :keyword %>
  <%= label_tag(:keyword, 'Palavra Chave')%>
  <%= select_tag(:structure_type, options_for_select(PowerGenerator.structure_types), include_blank: true) %>
  <%= label_tag(:structure_type, 'Tipo de Estrutura')%>
  <%= submit_tag('Buscar') %>
<% end %>

app/views/power_generators/recommended_search_result.html.erb
<% if @power_generators.nil?%>
  <div class="container" >
    <div class="container">
      <div align="center">
        <h3><%= flash[:error] %></h3>
      </div>
    </div>
  </div>
<% else %>
  <div class="container">
    <div align="center">
      <h3><%= flash[:notice] %></h3>
    </div>
  </div>
  <div class="container">
    <div align="center">
      <% render "search_form" %>
    </div>
  </div>
<% end %>

app/views/power_generators/search.html.erb
<div class="container">
  <div align="center">
    <h3><%= flash[:error] %></h3>
    <h3><%= flash[:notice] %></h3>
    </div>
</div>
<div>
  <%= link_to 'Recomendados para você', new_recommended_search_path %> 
</div>
<div class="container" >
  <% @power_generators.each do |power_generator| %>
    <div class="box card power_generator-card">
      <%= link_to image_tag(power_generator.image_url), power_generator %>
      <div class="power_generator-card__body">
        <h2><%= link_to (power_generator.name.upcase), power_generator %></h2>
        <p class="power_generator-card__price"><%= number_to_currency(power_generator.price, unit: "R$ ", precision: 2, :separator => ",", :delimiter => ".") %></p>
        <p><strong>Descrição: </strong><%= power_generator.description %></p>
      </div>
    </div>
  <% end %>
</div>

app/views/power_generators/show.html.erb
<h1><%= @power_generator.name %></h1>

<h3>Detalhes</h3>

<p>Tipo de estrutura:</p>
<p><%= @power_generator.structure_type %></p>
<p>Descrićão</p>
<p><%= @power_generator.description %></p>
<p>Fabricante</p>
<p><%= @power_generator.manufacturer %></p>
<p>Dimenções</p>
<p><%="#{@power_generator.height} x #{@power_generator.width} x #{@power_generator.lenght}" %></p>
<p>Produção de energia(kWp)</p>
<p><%= @power_generator.kwp %></p>

<h3>Preço</h3>
<h2><%= @power_generator.price %></h2>

<%= image_tag @power_generator.image_url %>

<%= link_to 'Voltar', root_path %>



<%= form_tag(power_generator_path, method: :get) do %>
    <input class="form-control form-control-lg" type="text" placeholder="CEP" name='cep'>
    <button type="submit" class="btn btn-outline-primary btn-lg">Calcular frete</button>
<% end %>
<% if @power_generator_freight.present?%>
    <%= render "form_cost" %>
<% end %>

<h3><%= flash[:error] %></h3>
<h3><%= flash[:notice] %></h3>

app/views/recommended_searches/new.html.erb
Nós queremos saber mais sobre o que você procura. Responda as perguntas abaixo:

<%= form_for @recommended_search do |f| %>
  <%= f.check_box(:lowest_cost) %>
  <%= f.label(:lowest_cost, "Menor Custo") %>
  <%= f.check_box(:lower_weight) %>
  <%= f.label(:lower_weight, "Menor Peso") %>
  <%= f.check_box(:lower_size) %>
  <%= f.label(:lower_size, "Menor Tamanho") %>
  <%= f.text_field(:keyword) %>
  <%= f.label(:keyword, "Palavra Chave") %>
  <%= f.label :structure_type, "Tipo de Estrutura" %>
  <%= f.select(:structure_type, PowerGenerator.structure_types, { include_blank: true }) %>  
  <%= f.submit('Buscar') %>
<% end %>

  
  

app/views/recommended_searches/show.html.erb
<%if @recommended_search.search_power_generators.empty? %>
  Que pena :( não conseguimos encontrar nenhum produto para você
<% else %>
  Nós indicamos para você:
  <div class="container" >
  <% @recommended_search.search_power_generators.each do |power_generator| %>
    <div class="box card power_generator-card">
      <%= link_to image_tag(power_generator.image_url), power_generator %>
      <div class="power_generator-card__body">
        <h2><%= link_to (power_generator.name), power_generator %></h2>
        <p class="power_generator-card__price"><%= number_to_currency(power_generator.price, unit: "R$ ", precision: 2, :separator => ",", :delimiter => ".") %></p>
        <p><strong>Descrição: </strong><%= power_generator.description %></p>
      </div>
    </div>
  <% end %>
</div>
<% end %>